<?php include "Dockerfile"; ?>

ENV MAGENTO_RUN_MODE developer
ENV UPLOAD_MAX_FILESIZE 64M

ADD etc/php-fpm.ini /usr/local/etc/php/conf.d/zz-magento.ini

ADD etc/php-fpm.conf /usr/local/etc/

RUN apt-get install vim -y

CMD ["php-fpm", "-F"]
